(function (g) {
  g.LLB = g.LLB || {};
  g.LLB.papers = g.LLB.papers || {};
  g.LLB.papers.k3003 = {
    id: "k3003",
    code: "K-3003",
    title: "Administrative Law",
    short: "Admin Law",
    blurb: "Rule of Law, SOP, delegated legislation, natural justice, writs, PIL, Lokpal/Lokayukta, tribunals/CAT \u2014 stub teasers only.",
    shelf: {
      primary: "CCS-recommended Administrative Law text (e.g. C.K. Takwani / I.P. Massey college list) + Constitution Arts. 32/226/323A\u2013B"
    },
    youtube: [
      { title: "Delegated legislation controls", search: "Delegated legislation judicial control India" },
      { title: "Natural justice principles", search: "Natural justice audi alteram partem bias" },
      { title: "Writs HMPCQ", search: "Five writs habeas mandamus certiorari" },
    ],
    topics: [
      {
        id: "a-intro",
        seq: 1,
        readAs: "Unit I \u00b7 intro",
        unit: 1,
        yield: "high",
        tags: ["definition", "scope", "evolution"],
        title: "Evolution, definition and scope of Administrative Law",
        summary: "Administrative law polices the executive\u2019s power: delegated legislation, discretion, natural justice, and judicial review. Trace why the welfare State bloated administration and why Dicey\u2019s discomfort still frames Indian essays.",
        explainer: "<p class=\"stub\"><strong>Shell stub.</strong> Full concept write-up pending. Work from the CCS syllabus heading, the bare Act / public case names, and your primary textbook \u2014 this card will expand without copying Unique/Nitin prose.</p><p>Draft path: define \u2192 essentials \u2192 statutes/cases \u2192 one distinction \u2192 close to the exam verb.</p>",
        diagram: {"type": "flow", "title": "Stub map \u2014 Evolution, definition and scope of Admin", "steps": ["Syllabus heading", "Bare-act hooks", "Essentials list", "Timed outline", "Seal"]},
        mnemonic: {"name": "TBD", "hook": "Mnemonic pending \u2014 write your own after the first textbook pass.", "recite": "Replace this when the full card lands."},
        cases: [],
        pyqs: [{"year": "theme", "section": "\u2014", "marks": "10\u201320", "q": "PYQ outline placeholder \u2014 public CCS themes will be mapped here later.", "outline": ["Open with a one-line definition tied to the statute or doctrine.", "Numbered essentials / ingredients.", "Two authorities or statutory hooks.", "One distinction or critique if the verb is \u2018critically examine\u2019.", "Close answering the exact question asked."]}],
        check: ["Can state the core definition without notes.", "Can list essentials in exam order.", "Can name at least two statutes, sections, or landmark cases for this heading."]
      },
      {
        id: "a-rol",
        seq: 2,
        readAs: "Unit I \u00b7 rule of law",
        unit: 1,
        yield: "high",
        tags: ["rule of law", "dicey"],
        title: "Rule of Law",
        summary: "Dicey\u2019s trio, modern restatements, and Indian reception (equality before law, supremacy of law, judicial review culture). Pair with a case that shows Rule of Law as a working doctrine, not a slogan.",
        explainer: "<p class=\"stub\"><strong>Shell stub.</strong> Full concept write-up pending. Work from the CCS syllabus heading, the bare Act / public case names, and your primary textbook \u2014 this card will expand without copying Unique/Nitin prose.</p><p>Draft path: define \u2192 essentials \u2192 statutes/cases \u2192 one distinction \u2192 close to the exam verb.</p>",
        diagram: {"type": "flow", "title": "Stub map \u2014 Rule of Law", "steps": ["Syllabus heading", "Bare-act hooks", "Essentials list", "Timed outline", "Seal"]},
        mnemonic: {"name": "TBD", "hook": "Mnemonic pending \u2014 write your own after the first textbook pass.", "recite": "Replace this when the full card lands."},
        cases: [],
        pyqs: [{"year": "theme", "section": "\u2014", "marks": "10\u201320", "q": "PYQ outline placeholder \u2014 public CCS themes will be mapped here later.", "outline": ["Open with a one-line definition tied to the statute or doctrine.", "Numbered essentials / ingredients.", "Two authorities or statutory hooks.", "One distinction or critique if the verb is \u2018critically examine\u2019.", "Close answering the exact question asked."]}],
        check: ["Can state the core definition without notes.", "Can list essentials in exam order.", "Can name at least two statutes, sections, or landmark cases for this heading."]
      },
      {
        id: "a-sop",
        seq: 3,
        readAs: "Unit I \u00b7 separation of powers",
        unit: 1,
        yield: "high",
        tags: ["separation of powers"],
        title: "Separation of Powers",
        summary: "Strict Montesquieu vs functional Indian separation: overlapping personnel, checks, and why delegated legislation and tribunals stress the classical picture. Use SOP as a gateway into legitimacy of administrative action.",
        explainer: "<p class=\"stub\"><strong>Shell stub.</strong> Full concept write-up pending. Work from the CCS syllabus heading, the bare Act / public case names, and your primary textbook \u2014 this card will expand without copying Unique/Nitin prose.</p><p>Draft path: define \u2192 essentials \u2192 statutes/cases \u2192 one distinction \u2192 close to the exam verb.</p>",
        diagram: {"type": "flow", "title": "Stub map \u2014 Separation of Powers", "steps": ["Syllabus heading", "Bare-act hooks", "Essentials list", "Timed outline", "Seal"]},
        mnemonic: {"name": "TBD", "hook": "Mnemonic pending \u2014 write your own after the first textbook pass.", "recite": "Replace this when the full card lands."},
        cases: [],
        pyqs: [{"year": "theme", "section": "\u2014", "marks": "10\u201320", "q": "PYQ outline placeholder \u2014 public CCS themes will be mapped here later.", "outline": ["Open with a one-line definition tied to the statute or doctrine.", "Numbered essentials / ingredients.", "Two authorities or statutory hooks.", "One distinction or critique if the verb is \u2018critically examine\u2019.", "Close answering the exact question asked."]}],
        check: ["Can state the core definition without notes.", "Can list essentials in exam order.", "Can name at least two statutes, sections, or landmark cases for this heading."]
      },
      {
        id: "a-delegated",
        seq: 4,
        readAs: "Unit II \u00b7 delegated legislation",
        unit: 2,
        yield: "high",
        tags: ["delegated legislation", "excessive delegation"],
        title: "Delegated Legislation \u2014 necessity, constitutionality, controls",
        summary: "Why legislatures delegate, constitutional limits (excessive delegation, essential legislative function), and controls \u2014 parliamentary, procedural, and judicial. This is a perennial 20-marker; outline necessity \u2192 limits \u2192 controls every time.",
        explainer: "<p class=\"stub\"><strong>Shell stub.</strong> Full concept write-up pending. Work from the CCS syllabus heading, the bare Act / public case names, and your primary textbook \u2014 this card will expand without copying Unique/Nitin prose.</p><p>Draft path: define \u2192 essentials \u2192 statutes/cases \u2192 one distinction \u2192 close to the exam verb.</p>",
        diagram: {"type": "flow", "title": "Stub map \u2014 Delegated Legislation", "steps": ["Syllabus heading", "Bare-act hooks", "Essentials list", "Timed outline", "Seal"]},
        mnemonic: {"name": "TBD", "hook": "Mnemonic pending \u2014 write your own after the first textbook pass.", "recite": "Replace this when the full card lands."},
        cases: [],
        pyqs: [{"year": "theme", "section": "\u2014", "marks": "10\u201320", "q": "PYQ outline placeholder \u2014 public CCS themes will be mapped here later.", "outline": ["Open with a one-line definition tied to the statute or doctrine.", "Numbered essentials / ingredients.", "Two authorities or statutory hooks.", "One distinction or critique if the verb is \u2018critically examine\u2019.", "Close answering the exact question asked."]}],
        check: ["Can state the core definition without notes.", "Can list essentials in exam order.", "Can name at least two statutes, sections, or landmark cases for this heading."]
      },
      {
        id: "a-nj",
        seq: 5,
        readAs: "Unit II \u00b7 natural justice",
        unit: 2,
        yield: "high",
        tags: ["natural justice", "bias", "audi alteram", "legitimate expectation"],
        title: "Natural Justice \u2014 bias, audi alteram, reasoned decisions, legitimate expectation",
        summary: "Nemo judex, audi alteram partem, speaking orders, and legitimate expectation are the hearing-rights toolkit. Know exceptions (emergency, pure legislation) and how Indian courts calibrate flexibility without emptying the doctrine.",
        explainer: "<p class=\"stub\"><strong>Shell stub.</strong> Full concept write-up pending. Work from the CCS syllabus heading, the bare Act / public case names, and your primary textbook \u2014 this card will expand without copying Unique/Nitin prose.</p><p>Draft path: define \u2192 essentials \u2192 statutes/cases \u2192 one distinction \u2192 close to the exam verb.</p>",
        diagram: {"type": "flow", "title": "Stub map \u2014 Natural Justice", "steps": ["Syllabus heading", "Bare-act hooks", "Essentials list", "Timed outline", "Seal"]},
        mnemonic: {"name": "TBD", "hook": "Mnemonic pending \u2014 write your own after the first textbook pass.", "recite": "Replace this when the full card lands."},
        cases: [],
        pyqs: [{"year": "theme", "section": "\u2014", "marks": "10\u201320", "q": "PYQ outline placeholder \u2014 public CCS themes will be mapped here later.", "outline": ["Open with a one-line definition tied to the statute or doctrine.", "Numbered essentials / ingredients.", "Two authorities or statutory hooks.", "One distinction or critique if the verb is \u2018critically examine\u2019.", "Close answering the exact question asked."]}],
        check: ["Can state the core definition without notes.", "Can list essentials in exam order.", "Can name at least two statutes, sections, or landmark cases for this heading."]
      },
      {
        id: "a-writs",
        seq: 6,
        readAs: "Unit III \u00b7 writs",
        unit: 3,
        yield: "high",
        tags: ["writs", "hmpcq", "judicial review"],
        title: "Writs \u2014 the five (HMPCQ)",
        summary: "Habeas corpus, mandamus, prohibition, certiorari, quo warranto \u2014 when each lies against administrative action. Art. 32/226 practice plus distinctions (certiorari vs prohibition) are high-yield drills.",
        explainer: "<p class=\"stub\"><strong>Shell stub.</strong> Full concept write-up pending. Work from the CCS syllabus heading, the bare Act / public case names, and your primary textbook \u2014 this card will expand without copying Unique/Nitin prose.</p><p>Draft path: define \u2192 essentials \u2192 statutes/cases \u2192 one distinction \u2192 close to the exam verb.</p>",
        diagram: {"type": "flow", "title": "Stub map \u2014 Writs", "steps": ["Syllabus heading", "Bare-act hooks", "Essentials list", "Timed outline", "Seal"]},
        mnemonic: {"name": "TBD", "hook": "Mnemonic pending \u2014 write your own after the first textbook pass.", "recite": "Replace this when the full card lands."},
        cases: [],
        pyqs: [{"year": "theme", "section": "\u2014", "marks": "10\u201320", "q": "PYQ outline placeholder \u2014 public CCS themes will be mapped here later.", "outline": ["Open with a one-line definition tied to the statute or doctrine.", "Numbered essentials / ingredients.", "Two authorities or statutory hooks.", "One distinction or critique if the verb is \u2018critically examine\u2019.", "Close answering the exact question asked."]}],
        check: ["Can state the core definition without notes.", "Can list essentials in exam order.", "Can name at least two statutes, sections, or landmark cases for this heading."]
      },
      {
        id: "a-pil",
        seq: 7,
        readAs: "Unit III \u00b7 PIL",
        unit: 3,
        yield: "high",
        tags: ["pil", "locus standi"],
        title: "Public Interest Litigation",
        summary: "PIL loosened locus standi to reach systemic administrative failure \u2014 with epistolary jurisdiction and continuing mandamus as tools. Know the promise and the misuse critique; CCS often wants both.",
        explainer: "<p class=\"stub\"><strong>Shell stub.</strong> Full concept write-up pending. Work from the CCS syllabus heading, the bare Act / public case names, and your primary textbook \u2014 this card will expand without copying Unique/Nitin prose.</p><p>Draft path: define \u2192 essentials \u2192 statutes/cases \u2192 one distinction \u2192 close to the exam verb.</p>",
        diagram: {"type": "flow", "title": "Stub map \u2014 Public Interest Litigation", "steps": ["Syllabus heading", "Bare-act hooks", "Essentials list", "Timed outline", "Seal"]},
        mnemonic: {"name": "TBD", "hook": "Mnemonic pending \u2014 write your own after the first textbook pass.", "recite": "Replace this when the full card lands."},
        cases: [],
        pyqs: [{"year": "theme", "section": "\u2014", "marks": "10\u201320", "q": "PYQ outline placeholder \u2014 public CCS themes will be mapped here later.", "outline": ["Open with a one-line definition tied to the statute or doctrine.", "Numbered essentials / ingredients.", "Two authorities or statutory hooks.", "One distinction or critique if the verb is \u2018critically examine\u2019.", "Close answering the exact question asked."]}],
        check: ["Can state the core definition without notes.", "Can list essentials in exam order.", "Can name at least two statutes, sections, or landmark cases for this heading."]
      },
      {
        id: "a-lokpal",
        seq: 8,
        readAs: "Unit III \u00b7 Lokpal & UP Lokayukta",
        unit: 3,
        yield: "standard",
        tags: ["lokpal", "lokayukta", "up"],
        title: "Lokpal and UP Lokayukta",
        summary: "Ombudsman-style anti-corruption institutions: Lokpal at the Centre and Lokayukta/UP framework at State level. Structure, complaint triggers, and limits relative to criminal investigation are the usual compare ask.",
        explainer: "<p class=\"stub\"><strong>Shell stub.</strong> Full concept write-up pending. Work from the CCS syllabus heading, the bare Act / public case names, and your primary textbook \u2014 this card will expand without copying Unique/Nitin prose.</p><p>Draft path: define \u2192 essentials \u2192 statutes/cases \u2192 one distinction \u2192 close to the exam verb.</p>",
        diagram: {"type": "flow", "title": "Stub map \u2014 Lokpal and UP Lokayukta", "steps": ["Syllabus heading", "Bare-act hooks", "Essentials list", "Timed outline", "Seal"]},
        mnemonic: {"name": "TBD", "hook": "Mnemonic pending \u2014 write your own after the first textbook pass.", "recite": "Replace this when the full card lands."},
        cases: [],
        pyqs: [{"year": "theme", "section": "\u2014", "marks": "10\u201320", "q": "PYQ outline placeholder \u2014 public CCS themes will be mapped here later.", "outline": ["Open with a one-line definition tied to the statute or doctrine.", "Numbered essentials / ingredients.", "Two authorities or statutory hooks.", "One distinction or critique if the verb is \u2018critically examine\u2019.", "Close answering the exact question asked."]}],
        check: ["Can state the core definition without notes.", "Can list essentials in exam order.", "Can name at least two statutes, sections, or landmark cases for this heading."]
      },
      {
        id: "a-tribunals",
        seq: 9,
        readAs: "Unit III \u00b7 tribunals / CAT",
        unit: 3,
        yield: "high",
        tags: ["tribunals", "cat", "323a"],
        title: "Administrative Tribunals and CAT",
        summary: "Tribunals as specialised justice under Arts. 323A/323B themes, CAT for central services, and the judicial-review / independence debates after key Supreme Court interventions. Position tribunals between departments and ordinary courts.",
        explainer: "<p class=\"stub\"><strong>Shell stub.</strong> Full concept write-up pending. Work from the CCS syllabus heading, the bare Act / public case names, and your primary textbook \u2014 this card will expand without copying Unique/Nitin prose.</p><p>Draft path: define \u2192 essentials \u2192 statutes/cases \u2192 one distinction \u2192 close to the exam verb.</p>",
        diagram: {"type": "flow", "title": "Stub map \u2014 Administrative Tribunals and CAT", "steps": ["Syllabus heading", "Bare-act hooks", "Essentials list", "Timed outline", "Seal"]},
        mnemonic: {"name": "TBD", "hook": "Mnemonic pending \u2014 write your own after the first textbook pass.", "recite": "Replace this when the full card lands."},
        cases: [],
        pyqs: [{"year": "theme", "section": "\u2014", "marks": "10\u201320", "q": "PYQ outline placeholder \u2014 public CCS themes will be mapped here later.", "outline": ["Open with a one-line definition tied to the statute or doctrine.", "Numbered essentials / ingredients.", "Two authorities or statutory hooks.", "One distinction or critique if the verb is \u2018critically examine\u2019.", "Close answering the exact question asked."]}],
        check: ["Can state the core definition without notes.", "Can list essentials in exam order.", "Can name at least two statutes, sections, or landmark cases for this heading."]
      },
    ]
  };
})(window);
