(function (g) {
  g.LLB = g.LLB || {};
  g.LLB.papers = g.LLB.papers || {};
  g.LLB.papers.k3001 = {
    id: "k3001",
    code: "K-3001",
    title: "Family Law\u2013II (Muslim Law)",
    short: "Muslim Law",
    blurb: "Sources, schools, marriage, mahr, talaq/DMMA\u2013Shah Bano overlay, wills, hiba, wakf, pre-emption, acknowledgement & guardianship \u2014 stub teasers only.",
    shelf: {
      primary: "CCS-recommended Muslim Law text (e.g. Aquil Ahmad / Aqil Ahmad or college list) + Dissolution of Muslim Marriages Act, Muslim Women Acts, CrPC 125 bare chapters"
    },
    youtube: [
      { title: "Muslim Law marriage & divorce overview", search: "Muslim Law nikah talaq judiciary CCS" },
      { title: "Shah Bano and maintenance", search: "Shah Bano CrPC 125 Muslim Women Act" },
      { title: "Wakf and hiba essentials", search: "Wakf Act mutawalli hiba essentials law" },
    ],
    topics: [
      {
        id: "m-intro",
        seq: 1,
        readAs: "Unit I \u00b7 introduction",
        unit: 1,
        yield: "high",
        tags: ["introduction", "muslim law", "personal law"],
        title: "Introduction to Muslim Law",
        summary: "Muslim personal law in India is a living system of family rules applied to Muslims in matters like marriage, dower, divorce, gifts, wills, and wakf. This card frames why Sem-3 treats Family Law\u2013II as a statutory-plus-classical mix, and how CCS expects you to open any essay with sources and applicability before diving into a remedy.",
        explainer: "<p class=\"stub\"><strong>Shell stub.</strong> Full concept write-up pending. Work from the CCS syllabus heading, the bare Act / public case names, and your primary textbook \u2014 this card will expand without copying Unique/Nitin prose.</p><p>Draft path: define \u2192 essentials \u2192 statutes/cases \u2192 one distinction \u2192 close to the exam verb.</p>",
        diagram: {"type": "flow", "title": "Stub map \u2014 Introduction to Muslim Law", "steps": ["Syllabus heading", "Bare-act hooks", "Essentials list", "Timed outline", "Seal"]},
        mnemonic: {"name": "TBD", "hook": "Mnemonic pending \u2014 write your own after the first textbook pass.", "recite": "Replace this when the full card lands."},
        cases: [],
        pyqs: [{"year": "theme", "section": "\u2014", "marks": "10\u201320", "q": "PYQ outline placeholder \u2014 public CCS themes will be mapped here later.", "outline": ["Open with a one-line definition tied to the statute or doctrine.", "Numbered essentials / ingredients.", "Two authorities or statutory hooks.", "One distinction or critique if the verb is \u2018critically examine\u2019.", "Close answering the exact question asked."]}],
        check: ["Can state the core definition without notes.", "Can list essentials in exam order.", "Can name at least two statutes, sections, or landmark cases for this heading."]
      },
      {
        id: "m-sources",
        seq: 2,
        readAs: "Unit I \u00b7 sources",
        unit: 1,
        yield: "high",
        tags: ["sources", "quran", "sunnah", "ijma", "qiyas"],
        title: "Sources of Muslim Law",
        summary: "Primary and secondary sources \u2014 Quran, Sunnah, Ijma, Qiyas, and later custom, legislation, and precedent \u2014 are the spine of almost every Family Law\u2013II opener. Know which source does what work in an Indian courtroom answer, and when a statute (DMMA, MWA, CrPC) overrides or supplements classical doctrine.",
        explainer: "<p class=\"stub\"><strong>Shell stub.</strong> Full concept write-up pending. Work from the CCS syllabus heading, the bare Act / public case names, and your primary textbook \u2014 this card will expand without copying Unique/Nitin prose.</p><p>Draft path: define \u2192 essentials \u2192 statutes/cases \u2192 one distinction \u2192 close to the exam verb.</p>",
        diagram: {"type": "flow", "title": "Stub map \u2014 Sources of Muslim Law", "steps": ["Syllabus heading", "Bare-act hooks", "Essentials list", "Timed outline", "Seal"]},
        mnemonic: {"name": "TBD", "hook": "Mnemonic pending \u2014 write your own after the first textbook pass.", "recite": "Replace this when the full card lands."},
        cases: [],
        pyqs: [{"year": "theme", "section": "\u2014", "marks": "10\u201320", "q": "PYQ outline placeholder \u2014 public CCS themes will be mapped here later.", "outline": ["Open with a one-line definition tied to the statute or doctrine.", "Numbered essentials / ingredients.", "Two authorities or statutory hooks.", "One distinction or critique if the verb is \u2018critically examine\u2019.", "Close answering the exact question asked."]}],
        check: ["Can state the core definition without notes.", "Can list essentials in exam order.", "Can name at least two statutes, sections, or landmark cases for this heading."]
      },
      {
        id: "m-schools",
        seq: 3,
        readAs: "Unit I \u00b7 schools",
        unit: 1,
        yield: "high",
        tags: ["schools", "hanafi", "shia", "sunni"],
        title: "Schools of Muslim Law",
        summary: "Sunni and Shia schools (Hanafi, Maliki, Shafi\u2018i, Hanbali; Ithna Ashari and others) diverge on marriage formalities, divorce forms, and inheritance flavour. CCS loves a short compare: name the school, one distinctive rule, and why Indian courts mostly meet Hanafi/Sunni facts unless parties plead otherwise.",
        explainer: "<p class=\"stub\"><strong>Shell stub.</strong> Full concept write-up pending. Work from the CCS syllabus heading, the bare Act / public case names, and your primary textbook \u2014 this card will expand without copying Unique/Nitin prose.</p><p>Draft path: define \u2192 essentials \u2192 statutes/cases \u2192 one distinction \u2192 close to the exam verb.</p>",
        diagram: {"type": "flow", "title": "Stub map \u2014 Schools of Muslim Law", "steps": ["Syllabus heading", "Bare-act hooks", "Essentials list", "Timed outline", "Seal"]},
        mnemonic: {"name": "TBD", "hook": "Mnemonic pending \u2014 write your own after the first textbook pass.", "recite": "Replace this when the full card lands."},
        cases: [],
        pyqs: [{"year": "theme", "section": "\u2014", "marks": "10\u201320", "q": "PYQ outline placeholder \u2014 public CCS themes will be mapped here later.", "outline": ["Open with a one-line definition tied to the statute or doctrine.", "Numbered essentials / ingredients.", "Two authorities or statutory hooks.", "One distinction or critique if the verb is \u2018critically examine\u2019.", "Close answering the exact question asked."]}],
        check: ["Can state the core definition without notes.", "Can list essentials in exam order.", "Can name at least two statutes, sections, or landmark cases for this heading."]
      },
      {
        id: "m-applicability",
        seq: 4,
        readAs: "Unit I \u00b7 applicability",
        unit: 1,
        yield: "high",
        tags: ["applicability", "muslim", "personal law"],
        title: "Applicability of Muslim Law",
        summary: "Who is a \u2018Muslim\u2019 for personal-law purposes, when does Muslim law apply as the rule of decision, and where does the Indian Succession Act or special statutes step in? Applicability is the gatekeeping unit \u2014 miss it and a perfect talaq essay still loses marks on parties and forum.",
        explainer: "<p class=\"stub\"><strong>Shell stub.</strong> Full concept write-up pending. Work from the CCS syllabus heading, the bare Act / public case names, and your primary textbook \u2014 this card will expand without copying Unique/Nitin prose.</p><p>Draft path: define \u2192 essentials \u2192 statutes/cases \u2192 one distinction \u2192 close to the exam verb.</p>",
        diagram: {"type": "flow", "title": "Stub map \u2014 Applicability of Muslim Law", "steps": ["Syllabus heading", "Bare-act hooks", "Essentials list", "Timed outline", "Seal"]},
        mnemonic: {"name": "TBD", "hook": "Mnemonic pending \u2014 write your own after the first textbook pass.", "recite": "Replace this when the full card lands."},
        cases: [],
        pyqs: [{"year": "theme", "section": "\u2014", "marks": "10\u201320", "q": "PYQ outline placeholder \u2014 public CCS themes will be mapped here later.", "outline": ["Open with a one-line definition tied to the statute or doctrine.", "Numbered essentials / ingredients.", "Two authorities or statutory hooks.", "One distinction or critique if the verb is \u2018critically examine\u2019.", "Close answering the exact question asked."]}],
        check: ["Can state the core definition without notes.", "Can list essentials in exam order.", "Can name at least two statutes, sections, or landmark cases for this heading."]
      },
      {
        id: "m-marriage",
        seq: 5,
        readAs: "Unit II \u00b7 marriage",
        unit: 2,
        yield: "high",
        tags: ["marriage", "nikah", "capacity"],
        title: "Marriage (Nikah)",
        summary: "Nikah is a civil contract with religious colour: proposal, acceptance, capacity, and absence of prohibitions. Essentials, classification (valid/void/irregular in Sunni framing), and mut\u2018a debates are stock 10/20-markers \u2014 keep the essentials list cold and distinguish void from irregular.",
        explainer: "<p class=\"stub\"><strong>Shell stub.</strong> Full concept write-up pending. Work from the CCS syllabus heading, the bare Act / public case names, and your primary textbook \u2014 this card will expand without copying Unique/Nitin prose.</p><p>Draft path: define \u2192 essentials \u2192 statutes/cases \u2192 one distinction \u2192 close to the exam verb.</p>",
        diagram: {"type": "flow", "title": "Stub map \u2014 Marriage (Nikah)", "steps": ["Syllabus heading", "Bare-act hooks", "Essentials list", "Timed outline", "Seal"]},
        mnemonic: {"name": "TBD", "hook": "Mnemonic pending \u2014 write your own after the first textbook pass.", "recite": "Replace this when the full card lands."},
        cases: [],
        pyqs: [{"year": "theme", "section": "\u2014", "marks": "10\u201320", "q": "PYQ outline placeholder \u2014 public CCS themes will be mapped here later.", "outline": ["Open with a one-line definition tied to the statute or doctrine.", "Numbered essentials / ingredients.", "Two authorities or statutory hooks.", "One distinction or critique if the verb is \u2018critically examine\u2019.", "Close answering the exact question asked."]}],
        check: ["Can state the core definition without notes.", "Can list essentials in exam order.", "Can name at least two statutes, sections, or landmark cases for this heading."]
      },
      {
        id: "m-mahr",
        seq: 6,
        readAs: "Unit II \u00b7 mahr",
        unit: 2,
        yield: "high",
        tags: ["mahr", "dower"],
        title: "Mahr (Dower)",
        summary: "Mahr is the wife\u2019s proprietary right arising from marriage \u2014 prompt, deferred, specified, or proper. Quantum, enforcement, and widow\u2019s lien themes recur every few years; treat mahr as debt-like property, not a gift, unless the question forces a distinction.",
        explainer: "<p class=\"stub\"><strong>Shell stub.</strong> Full concept write-up pending. Work from the CCS syllabus heading, the bare Act / public case names, and your primary textbook \u2014 this card will expand without copying Unique/Nitin prose.</p><p>Draft path: define \u2192 essentials \u2192 statutes/cases \u2192 one distinction \u2192 close to the exam verb.</p>",
        diagram: {"type": "flow", "title": "Stub map \u2014 Mahr (Dower)", "steps": ["Syllabus heading", "Bare-act hooks", "Essentials list", "Timed outline", "Seal"]},
        mnemonic: {"name": "TBD", "hook": "Mnemonic pending \u2014 write your own after the first textbook pass.", "recite": "Replace this when the full card lands."},
        cases: [],
        pyqs: [{"year": "theme", "section": "\u2014", "marks": "10\u201320", "q": "PYQ outline placeholder \u2014 public CCS themes will be mapped here later.", "outline": ["Open with a one-line definition tied to the statute or doctrine.", "Numbered essentials / ingredients.", "Two authorities or statutory hooks.", "One distinction or critique if the verb is \u2018critically examine\u2019.", "Close answering the exact question asked."]}],
        check: ["Can state the core definition without notes.", "Can list essentials in exam order.", "Can name at least two statutes, sections, or landmark cases for this heading."]
      },
      {
        id: "m-divorce",
        seq: 7,
        readAs: "Unit II \u00b7 divorce / talaq",
        unit: 2,
        yield: "high",
        tags: ["divorce", "talaq", "khula", "mubarat"],
        title: "Divorce and Talaq",
        summary: "Modes of dissolution \u2014 talaq (forms and controversy), khula, mubarat, ila, zihar, lian, and judicial divorce under statute \u2014 are the paper\u2019s loudest exam magnet. Map each mode to who initiates, what formalities matter post-Shayara Bano line, and how maintenance questions hitch on.",
        explainer: "<p class=\"stub\"><strong>Shell stub.</strong> Full concept write-up pending. Work from the CCS syllabus heading, the bare Act / public case names, and your primary textbook \u2014 this card will expand without copying Unique/Nitin prose.</p><p>Draft path: define \u2192 essentials \u2192 statutes/cases \u2192 one distinction \u2192 close to the exam verb.</p>",
        diagram: {"type": "flow", "title": "Stub map \u2014 Divorce and Talaq", "steps": ["Syllabus heading", "Bare-act hooks", "Essentials list", "Timed outline", "Seal"]},
        mnemonic: {"name": "TBD", "hook": "Mnemonic pending \u2014 write your own after the first textbook pass.", "recite": "Replace this when the full card lands."},
        cases: [],
        pyqs: [{"year": "theme", "section": "\u2014", "marks": "10\u201320", "q": "PYQ outline placeholder \u2014 public CCS themes will be mapped here later.", "outline": ["Open with a one-line definition tied to the statute or doctrine.", "Numbered essentials / ingredients.", "Two authorities or statutory hooks.", "One distinction or critique if the verb is \u2018critically examine\u2019.", "Close answering the exact question asked."]}],
        check: ["Can state the core definition without notes.", "Can list essentials in exam order.", "Can name at least two statutes, sections, or landmark cases for this heading."]
      },
      {
        id: "m-shahbano",
        seq: 8,
        readAs: "Unit II \u00b7 statutory overlay",
        unit: 2,
        yield: "high",
        tags: ["shah bano", "dmma", "mwa", "crpc 125", "maintenance"],
        title: "DMMA, MWA, CrPC 125 & Shah Bano theme",
        summary: "The Shah Bano arc, the Muslim Women (Protection of Rights on Divorce) Act, DMMA judicial divorce, and CrPC 125 maintenance sit at the statute\u2013personal-law junction. Keep a separate card so the constitutional maintenance story does not bury classical talaq essentials \u2014 examiners often want both.",
        explainer: "<p class=\"stub\"><strong>Shell stub.</strong> Full concept write-up pending. Work from the CCS syllabus heading, the bare Act / public case names, and your primary textbook \u2014 this card will expand without copying Unique/Nitin prose.</p><p>Draft path: define \u2192 essentials \u2192 statutes/cases \u2192 one distinction \u2192 close to the exam verb.</p>",
        diagram: {"type": "flow", "title": "Stub map \u2014 DMMA, MWA, CrPC 125 & Shah Bano theme", "steps": ["Syllabus heading", "Bare-act hooks", "Essentials list", "Timed outline", "Seal"]},
        mnemonic: {"name": "TBD", "hook": "Mnemonic pending \u2014 write your own after the first textbook pass.", "recite": "Replace this when the full card lands."},
        cases: [],
        pyqs: [{"year": "theme", "section": "\u2014", "marks": "10\u201320", "q": "PYQ outline placeholder \u2014 public CCS themes will be mapped here later.", "outline": ["Open with a one-line definition tied to the statute or doctrine.", "Numbered essentials / ingredients.", "Two authorities or statutory hooks.", "One distinction or critique if the verb is \u2018critically examine\u2019.", "Close answering the exact question asked."]}],
        check: ["Can state the core definition without notes.", "Can list essentials in exam order.", "Can name at least two statutes, sections, or landmark cases for this heading."]
      },
      {
        id: "m-wills",
        seq: 9,
        readAs: "Unit III \u00b7 wills",
        unit: 3,
        yield: "standard",
        tags: ["wills", "wasiyat", "bequest"],
        title: "Wills (Wasiyat)",
        summary: "A Muslim may generally bequeath up to one-third of the estate to a non-heir without heir consent; formalities and revocation rules differ from the Indian Succession Act template. Essentials, limits, and consent of heirs are the usual short-note spine.",
        explainer: "<p class=\"stub\"><strong>Shell stub.</strong> Full concept write-up pending. Work from the CCS syllabus heading, the bare Act / public case names, and your primary textbook \u2014 this card will expand without copying Unique/Nitin prose.</p><p>Draft path: define \u2192 essentials \u2192 statutes/cases \u2192 one distinction \u2192 close to the exam verb.</p>",
        diagram: {"type": "flow", "title": "Stub map \u2014 Wills (Wasiyat)", "steps": ["Syllabus heading", "Bare-act hooks", "Essentials list", "Timed outline", "Seal"]},
        mnemonic: {"name": "TBD", "hook": "Mnemonic pending \u2014 write your own after the first textbook pass.", "recite": "Replace this when the full card lands."},
        cases: [],
        pyqs: [{"year": "theme", "section": "\u2014", "marks": "10\u201320", "q": "PYQ outline placeholder \u2014 public CCS themes will be mapped here later.", "outline": ["Open with a one-line definition tied to the statute or doctrine.", "Numbered essentials / ingredients.", "Two authorities or statutory hooks.", "One distinction or critique if the verb is \u2018critically examine\u2019.", "Close answering the exact question asked."]}],
        check: ["Can state the core definition without notes.", "Can list essentials in exam order.", "Can name at least two statutes, sections, or landmark cases for this heading."]
      },
      {
        id: "m-gifts",
        seq: 10,
        readAs: "Unit III \u00b7 gifts",
        unit: 3,
        yield: "high",
        tags: ["gifts", "hiba", "possession"],
        title: "Gifts (Hiba)",
        summary: "Hiba needs declaration, acceptance, and delivery of possession \u2014 with classic exceptions (donor\u2013donee living together; guardian\u2013ward). Distinguish hiba from will and from sale; conditional and contingent gifts are common traps.",
        explainer: "<p class=\"stub\"><strong>Shell stub.</strong> Full concept write-up pending. Work from the CCS syllabus heading, the bare Act / public case names, and your primary textbook \u2014 this card will expand without copying Unique/Nitin prose.</p><p>Draft path: define \u2192 essentials \u2192 statutes/cases \u2192 one distinction \u2192 close to the exam verb.</p>",
        diagram: {"type": "flow", "title": "Stub map \u2014 Gifts (Hiba)", "steps": ["Syllabus heading", "Bare-act hooks", "Essentials list", "Timed outline", "Seal"]},
        mnemonic: {"name": "TBD", "hook": "Mnemonic pending \u2014 write your own after the first textbook pass.", "recite": "Replace this when the full card lands."},
        cases: [],
        pyqs: [{"year": "theme", "section": "\u2014", "marks": "10\u201320", "q": "PYQ outline placeholder \u2014 public CCS themes will be mapped here later.", "outline": ["Open with a one-line definition tied to the statute or doctrine.", "Numbered essentials / ingredients.", "Two authorities or statutory hooks.", "One distinction or critique if the verb is \u2018critically examine\u2019.", "Close answering the exact question asked."]}],
        check: ["Can state the core definition without notes.", "Can list essentials in exam order.", "Can name at least two statutes, sections, or landmark cases for this heading."]
      },
      {
        id: "m-wakf",
        seq: 11,
        readAs: "Unit III \u00b7 wakf",
        unit: 3,
        yield: "high",
        tags: ["wakf", "waqf", "mutawalli"],
        title: "Wakf",
        summary: "Wakf is permanent dedication of property for religious or charitable purposes under Muslim law, now heavily statutory under the Waqf Acts framework. Creation, mutawalli, objects, and dedication essentials are high-yield; flag statutory updates without inventing section numbers you have not verified.",
        explainer: "<p class=\"stub\"><strong>Shell stub.</strong> Full concept write-up pending. Work from the CCS syllabus heading, the bare Act / public case names, and your primary textbook \u2014 this card will expand without copying Unique/Nitin prose.</p><p>Draft path: define \u2192 essentials \u2192 statutes/cases \u2192 one distinction \u2192 close to the exam verb.</p>",
        diagram: {"type": "flow", "title": "Stub map \u2014 Wakf", "steps": ["Syllabus heading", "Bare-act hooks", "Essentials list", "Timed outline", "Seal"]},
        mnemonic: {"name": "TBD", "hook": "Mnemonic pending \u2014 write your own after the first textbook pass.", "recite": "Replace this when the full card lands."},
        cases: [],
        pyqs: [{"year": "theme", "section": "\u2014", "marks": "10\u201320", "q": "PYQ outline placeholder \u2014 public CCS themes will be mapped here later.", "outline": ["Open with a one-line definition tied to the statute or doctrine.", "Numbered essentials / ingredients.", "Two authorities or statutory hooks.", "One distinction or critique if the verb is \u2018critically examine\u2019.", "Close answering the exact question asked."]}],
        check: ["Can state the core definition without notes.", "Can list essentials in exam order.", "Can name at least two statutes, sections, or landmark cases for this heading."]
      },
      {
        id: "m-preemption",
        seq: 12,
        readAs: "Unit III \u00b7 pre-emption",
        unit: 3,
        yield: "standard",
        tags: ["pre-emption", "shufa"],
        title: "Pre-emption (Shufa)",
        summary: "Pre-emption is the preferential right to buy neighbouring or co-owned property when it is sold \u2014 classical classes of shafi and constitutional scrutiny of the doctrine. Know who can claim, when the right arises, and how modern property policy has narrowed it.",
        explainer: "<p class=\"stub\"><strong>Shell stub.</strong> Full concept write-up pending. Work from the CCS syllabus heading, the bare Act / public case names, and your primary textbook \u2014 this card will expand without copying Unique/Nitin prose.</p><p>Draft path: define \u2192 essentials \u2192 statutes/cases \u2192 one distinction \u2192 close to the exam verb.</p>",
        diagram: {"type": "flow", "title": "Stub map \u2014 Pre-emption (Shufa)", "steps": ["Syllabus heading", "Bare-act hooks", "Essentials list", "Timed outline", "Seal"]},
        mnemonic: {"name": "TBD", "hook": "Mnemonic pending \u2014 write your own after the first textbook pass.", "recite": "Replace this when the full card lands."},
        cases: [],
        pyqs: [{"year": "theme", "section": "\u2014", "marks": "10\u201320", "q": "PYQ outline placeholder \u2014 public CCS themes will be mapped here later.", "outline": ["Open with a one-line definition tied to the statute or doctrine.", "Numbered essentials / ingredients.", "Two authorities or statutory hooks.", "One distinction or critique if the verb is \u2018critically examine\u2019.", "Close answering the exact question asked."]}],
        check: ["Can state the core definition without notes.", "Can list essentials in exam order.", "Can name at least two statutes, sections, or landmark cases for this heading."]
      },
      {
        id: "m-ack-guard",
        seq: 13,
        readAs: "Unit III \u00b7 acknowledgement & guardianship",
        unit: 3,
        yield: "standard",
        tags: ["acknowledgement", "guardianship", "legitimacy"],
        title: "Acknowledgement & Guardianship",
        summary: "Acknowledgement of paternity/legitimacy and guardianship of person and property are linked status topics. Map who is a natural guardian, when the court intervenes, and how acknowledgement differs from adoption (which classical Muslim law does not recognise in the Hindu sense).",
        explainer: "<p class=\"stub\"><strong>Shell stub.</strong> Full concept write-up pending. Work from the CCS syllabus heading, the bare Act / public case names, and your primary textbook \u2014 this card will expand without copying Unique/Nitin prose.</p><p>Draft path: define \u2192 essentials \u2192 statutes/cases \u2192 one distinction \u2192 close to the exam verb.</p>",
        diagram: {"type": "flow", "title": "Stub map \u2014 Acknowledgement & Guardianship", "steps": ["Syllabus heading", "Bare-act hooks", "Essentials list", "Timed outline", "Seal"]},
        mnemonic: {"name": "TBD", "hook": "Mnemonic pending \u2014 write your own after the first textbook pass.", "recite": "Replace this when the full card lands."},
        cases: [],
        pyqs: [{"year": "theme", "section": "\u2014", "marks": "10\u201320", "q": "PYQ outline placeholder \u2014 public CCS themes will be mapped here later.", "outline": ["Open with a one-line definition tied to the statute or doctrine.", "Numbered essentials / ingredients.", "Two authorities or statutory hooks.", "One distinction or critique if the verb is \u2018critically examine\u2019.", "Close answering the exact question asked."]}],
        check: ["Can state the core definition without notes.", "Can list essentials in exam order.", "Can name at least two statutes, sections, or landmark cases for this heading."]
      },
    ]
  };
})(window);
