(function (g) {
  g.LLB = g.LLB || {};
  g.LLB.papers = g.LLB.papers || {};
  g.LLB.papers.k3002 = {
    id: "k3002",
    code: "K-3002",
    title: "Public International Law",
    short: "PIL",
    blurb: "Theory, sources, IL\u2013municipal law, State topics, war/disputes cluster, Law of the Sea \u2014 stub teasers only.",
    shelf: {
      primary: "CCS-recommended PIL text (e.g. S.K. Kapoor / M.P. Tandon college list) + UN Charter / ICJ Statute extracts"
    },
    youtube: [
      { title: "Sources of International Law Art. 38", search: "Article 38 ICJ sources of international law" },
      { title: "Law of the Sea UNCLOS zones", search: "UNCLOS territorial sea EEZ continental shelf" },
      { title: "Recognition and succession", search: "Recognition of states international law judiciary" },
    ],
    topics: [
      {
        id: "p-theory",
        seq: 1,
        readAs: "Unit I \u00b7 theory",
        unit: 1,
        yield: "high",
        tags: ["theory", "nature", "austin"],
        title: "Theoretical foundation of International Law",
        summary: "Is international law \u2018real\u2019 law? Austin\u2019s scepticism, consent theories, and modern institutional practice set the opener for Public International Law. CCS expects you to defend IL\u2019s legal character with sanctions short of a world police \u2014 reputation, reciprocity, and institutional consequences.",
        explainer: "<p class=\"stub\"><strong>Shell stub.</strong> Full concept write-up pending. Work from the CCS syllabus heading, the bare Act / public case names, and your primary textbook \u2014 this card will expand without copying Unique/Nitin prose.</p><p>Draft path: define \u2192 essentials \u2192 statutes/cases \u2192 one distinction \u2192 close to the exam verb.</p>",
        diagram: {"type": "flow", "title": "Stub map \u2014 Theoretical foundation of International ", "steps": ["Syllabus heading", "Bare-act hooks", "Essentials list", "Timed outline", "Seal"]},
        mnemonic: {"name": "TBD", "hook": "Mnemonic pending \u2014 write your own after the first textbook pass.", "recite": "Replace this when the full card lands."},
        cases: [],
        pyqs: [{"year": "theme", "section": "\u2014", "marks": "10\u201320", "q": "PYQ outline placeholder \u2014 public CCS themes will be mapped here later.", "outline": ["Open with a one-line definition tied to the statute or doctrine.", "Numbered essentials / ingredients.", "Two authorities or statutory hooks.", "One distinction or critique if the verb is \u2018critically examine\u2019.", "Close answering the exact question asked."]}],
        check: ["Can state the core definition without notes.", "Can list essentials in exam order.", "Can name at least two statutes, sections, or landmark cases for this heading."]
      },
      {
        id: "p-sources",
        seq: 2,
        readAs: "Unit I \u00b7 sources",
        unit: 1,
        yield: "high",
        tags: ["sources", "article 38", "custom", "treaty"],
        title: "Sources of International Law",
        summary: "Article 38(1) ICJ Statute \u2014 treaties, custom, general principles, and subsidiary means \u2014 is the non-negotiable map. Soft law, Jus cogens, and erga omnes obligations are frequent upgrades on a basic sources essay.",
        explainer: "<p class=\"stub\"><strong>Shell stub.</strong> Full concept write-up pending. Work from the CCS syllabus heading, the bare Act / public case names, and your primary textbook \u2014 this card will expand without copying Unique/Nitin prose.</p><p>Draft path: define \u2192 essentials \u2192 statutes/cases \u2192 one distinction \u2192 close to the exam verb.</p>",
        diagram: {"type": "flow", "title": "Stub map \u2014 Sources of International Law", "steps": ["Syllabus heading", "Bare-act hooks", "Essentials list", "Timed outline", "Seal"]},
        mnemonic: {"name": "TBD", "hook": "Mnemonic pending \u2014 write your own after the first textbook pass.", "recite": "Replace this when the full card lands."},
        cases: [],
        pyqs: [{"year": "theme", "section": "\u2014", "marks": "10\u201320", "q": "PYQ outline placeholder \u2014 public CCS themes will be mapped here later.", "outline": ["Open with a one-line definition tied to the statute or doctrine.", "Numbered essentials / ingredients.", "Two authorities or statutory hooks.", "One distinction or critique if the verb is \u2018critically examine\u2019.", "Close answering the exact question asked."]}],
        check: ["Can state the core definition without notes.", "Can list essentials in exam order.", "Can name at least two statutes, sections, or landmark cases for this heading."]
      },
      {
        id: "p-municipal",
        seq: 3,
        readAs: "Unit I \u00b7 IL & municipal law",
        unit: 1,
        yield: "high",
        tags: ["municipal", "monism", "dualism"],
        title: "International Law and Municipal Law",
        summary: "Monism vs dualism, incorporation vs transformation, and how Indian courts use Article 51 / treaty doctrine without making every treaty self-executing. Keep a clean table and one Indian illustration ready.",
        explainer: "<p class=\"stub\"><strong>Shell stub.</strong> Full concept write-up pending. Work from the CCS syllabus heading, the bare Act / public case names, and your primary textbook \u2014 this card will expand without copying Unique/Nitin prose.</p><p>Draft path: define \u2192 essentials \u2192 statutes/cases \u2192 one distinction \u2192 close to the exam verb.</p>",
        diagram: {"type": "flow", "title": "Stub map \u2014 International Law and Municipal Law", "steps": ["Syllabus heading", "Bare-act hooks", "Essentials list", "Timed outline", "Seal"]},
        mnemonic: {"name": "TBD", "hook": "Mnemonic pending \u2014 write your own after the first textbook pass.", "recite": "Replace this when the full card lands."},
        cases: [],
        pyqs: [{"year": "theme", "section": "\u2014", "marks": "10\u201320", "q": "PYQ outline placeholder \u2014 public CCS themes will be mapped here later.", "outline": ["Open with a one-line definition tied to the statute or doctrine.", "Numbered essentials / ingredients.", "Two authorities or statutory hooks.", "One distinction or critique if the verb is \u2018critically examine\u2019.", "Close answering the exact question asked."]}],
        check: ["Can state the core definition without notes.", "Can list essentials in exam order.", "Can name at least two statutes, sections, or landmark cases for this heading."]
      },
      {
        id: "p-state-sov",
        seq: 4,
        readAs: "Unit II \u00b7 sovereignty & territory",
        unit: 2,
        yield: "high",
        tags: ["sovereignty", "territory"],
        title: "State \u2014 sovereignty and territory",
        summary: "Sovereignty, modes of acquiring and losing territory, and boundaries disputes are classic State-law material. Pair doctrinal labels (cession, occupation, prescription, accretion, conquest\u2019s modern status) with one map-style example.",
        explainer: "<p class=\"stub\"><strong>Shell stub.</strong> Full concept write-up pending. Work from the CCS syllabus heading, the bare Act / public case names, and your primary textbook \u2014 this card will expand without copying Unique/Nitin prose.</p><p>Draft path: define \u2192 essentials \u2192 statutes/cases \u2192 one distinction \u2192 close to the exam verb.</p>",
        diagram: {"type": "flow", "title": "Stub map \u2014 State", "steps": ["Syllabus heading", "Bare-act hooks", "Essentials list", "Timed outline", "Seal"]},
        mnemonic: {"name": "TBD", "hook": "Mnemonic pending \u2014 write your own after the first textbook pass.", "recite": "Replace this when the full card lands."},
        cases: [],
        pyqs: [{"year": "theme", "section": "\u2014", "marks": "10\u201320", "q": "PYQ outline placeholder \u2014 public CCS themes will be mapped here later.", "outline": ["Open with a one-line definition tied to the statute or doctrine.", "Numbered essentials / ingredients.", "Two authorities or statutory hooks.", "One distinction or critique if the verb is \u2018critically examine\u2019.", "Close answering the exact question asked."]}],
        check: ["Can state the core definition without notes.", "Can list essentials in exam order.", "Can name at least two statutes, sections, or landmark cases for this heading."]
      },
      {
        id: "p-recognition",
        seq: 5,
        readAs: "Unit II \u00b7 recognition & succession",
        unit: 2,
        yield: "high",
        tags: ["recognition", "succession"],
        title: "Recognition and State succession",
        summary: "Recognition of States and governments (declaratory vs constitutive), de facto/de jure, and succession to treaties/debts after break-up or merger. Examiners love problem facts: new regime, unpaid loans, unfinished treaties.",
        explainer: "<p class=\"stub\"><strong>Shell stub.</strong> Full concept write-up pending. Work from the CCS syllabus heading, the bare Act / public case names, and your primary textbook \u2014 this card will expand without copying Unique/Nitin prose.</p><p>Draft path: define \u2192 essentials \u2192 statutes/cases \u2192 one distinction \u2192 close to the exam verb.</p>",
        diagram: {"type": "flow", "title": "Stub map \u2014 Recognition and State succession", "steps": ["Syllabus heading", "Bare-act hooks", "Essentials list", "Timed outline", "Seal"]},
        mnemonic: {"name": "TBD", "hook": "Mnemonic pending \u2014 write your own after the first textbook pass.", "recite": "Replace this when the full card lands."},
        cases: [],
        pyqs: [{"year": "theme", "section": "\u2014", "marks": "10\u201320", "q": "PYQ outline placeholder \u2014 public CCS themes will be mapped here later.", "outline": ["Open with a one-line definition tied to the statute or doctrine.", "Numbered essentials / ingredients.", "Two authorities or statutory hooks.", "One distinction or critique if the verb is \u2018critically examine\u2019.", "Close answering the exact question asked."]}],
        check: ["Can state the core definition without notes.", "Can list essentials in exam order.", "Can name at least two statutes, sections, or landmark cases for this heading."]
      },
      {
        id: "p-intervention",
        seq: 6,
        readAs: "Unit II \u00b7 intervention",
        unit: 2,
        yield: "high",
        tags: ["intervention", "use of force"],
        title: "Intervention",
        summary: "Prohibition on intervention, UN Charter constraints, and contested exceptions (self-defence, invitation, humanitarian claims). Write the rule first, then the controversy \u2014 do not open with the exception.",
        explainer: "<p class=\"stub\"><strong>Shell stub.</strong> Full concept write-up pending. Work from the CCS syllabus heading, the bare Act / public case names, and your primary textbook \u2014 this card will expand without copying Unique/Nitin prose.</p><p>Draft path: define \u2192 essentials \u2192 statutes/cases \u2192 one distinction \u2192 close to the exam verb.</p>",
        diagram: {"type": "flow", "title": "Stub map \u2014 Intervention", "steps": ["Syllabus heading", "Bare-act hooks", "Essentials list", "Timed outline", "Seal"]},
        mnemonic: {"name": "TBD", "hook": "Mnemonic pending \u2014 write your own after the first textbook pass.", "recite": "Replace this when the full card lands."},
        cases: [],
        pyqs: [{"year": "theme", "section": "\u2014", "marks": "10\u201320", "q": "PYQ outline placeholder \u2014 public CCS themes will be mapped here later.", "outline": ["Open with a one-line definition tied to the statute or doctrine.", "Numbered essentials / ingredients.", "Two authorities or statutory hooks.", "One distinction or critique if the verb is \u2018critically examine\u2019.", "Close answering the exact question asked."]}],
        check: ["Can state the core definition without notes.", "Can list essentials in exam order.", "Can name at least two statutes, sections, or landmark cases for this heading."]
      },
      {
        id: "p-nationality",
        seq: 7,
        readAs: "Unit II \u00b7 nationality",
        unit: 2,
        yield: "standard",
        tags: ["nationality", "diplomatic protection"],
        title: "Nationality",
        summary: "Nationality as the link between individual and State: acquisition, dual nationality frictions, and diplomatic protection. Distinguish nationality from domicile and from refugee status.",
        explainer: "<p class=\"stub\"><strong>Shell stub.</strong> Full concept write-up pending. Work from the CCS syllabus heading, the bare Act / public case names, and your primary textbook \u2014 this card will expand without copying Unique/Nitin prose.</p><p>Draft path: define \u2192 essentials \u2192 statutes/cases \u2192 one distinction \u2192 close to the exam verb.</p>",
        diagram: {"type": "flow", "title": "Stub map \u2014 Nationality", "steps": ["Syllabus heading", "Bare-act hooks", "Essentials list", "Timed outline", "Seal"]},
        mnemonic: {"name": "TBD", "hook": "Mnemonic pending \u2014 write your own after the first textbook pass.", "recite": "Replace this when the full card lands."},
        cases: [],
        pyqs: [{"year": "theme", "section": "\u2014", "marks": "10\u201320", "q": "PYQ outline placeholder \u2014 public CCS themes will be mapped here later.", "outline": ["Open with a one-line definition tied to the statute or doctrine.", "Numbered essentials / ingredients.", "Two authorities or statutory hooks.", "One distinction or critique if the verb is \u2018critically examine\u2019.", "Close answering the exact question asked."]}],
        check: ["Can state the core definition without notes.", "Can list essentials in exam order.", "Can name at least two statutes, sections, or landmark cases for this heading."]
      },
      {
        id: "p-diplomats",
        seq: 8,
        readAs: "Unit II \u00b7 diplomats",
        unit: 2,
        yield: "high",
        tags: ["diplomats", "immunity", "vienna"],
        title: "Diplomatic agents",
        summary: "Vienna Convention themes: inviolability, immunity, persona non grata, and premises. Short notes love lists \u2014 privileges with a purpose (functional necessity), not aristocratic folklore.",
        explainer: "<p class=\"stub\"><strong>Shell stub.</strong> Full concept write-up pending. Work from the CCS syllabus heading, the bare Act / public case names, and your primary textbook \u2014 this card will expand without copying Unique/Nitin prose.</p><p>Draft path: define \u2192 essentials \u2192 statutes/cases \u2192 one distinction \u2192 close to the exam verb.</p>",
        diagram: {"type": "flow", "title": "Stub map \u2014 Diplomatic agents", "steps": ["Syllabus heading", "Bare-act hooks", "Essentials list", "Timed outline", "Seal"]},
        mnemonic: {"name": "TBD", "hook": "Mnemonic pending \u2014 write your own after the first textbook pass.", "recite": "Replace this when the full card lands."},
        cases: [],
        pyqs: [{"year": "theme", "section": "\u2014", "marks": "10\u201320", "q": "PYQ outline placeholder \u2014 public CCS themes will be mapped here later.", "outline": ["Open with a one-line definition tied to the statute or doctrine.", "Numbered essentials / ingredients.", "Two authorities or statutory hooks.", "One distinction or critique if the verb is \u2018critically examine\u2019.", "Close answering the exact question asked."]}],
        check: ["Can state the core definition without notes.", "Can list essentials in exam order.", "Can name at least two statutes, sections, or landmark cases for this heading."]
      },
      {
        id: "p-extradition",
        seq: 9,
        readAs: "Unit II \u00b7 extradition",
        unit: 2,
        yield: "high",
        tags: ["extradition"],
        title: "Extradition",
        summary: "Extradition is treaty-and-statute driven: double criminality, political offence exception, specialty, and Indian practice under the Extradition Act. Problem questions usually hide a political-offence or nationality twist.",
        explainer: "<p class=\"stub\"><strong>Shell stub.</strong> Full concept write-up pending. Work from the CCS syllabus heading, the bare Act / public case names, and your primary textbook \u2014 this card will expand without copying Unique/Nitin prose.</p><p>Draft path: define \u2192 essentials \u2192 statutes/cases \u2192 one distinction \u2192 close to the exam verb.</p>",
        diagram: {"type": "flow", "title": "Stub map \u2014 Extradition", "steps": ["Syllabus heading", "Bare-act hooks", "Essentials list", "Timed outline", "Seal"]},
        mnemonic: {"name": "TBD", "hook": "Mnemonic pending \u2014 write your own after the first textbook pass.", "recite": "Replace this when the full card lands."},
        cases: [],
        pyqs: [{"year": "theme", "section": "\u2014", "marks": "10\u201320", "q": "PYQ outline placeholder \u2014 public CCS themes will be mapped here later.", "outline": ["Open with a one-line definition tied to the statute or doctrine.", "Numbered essentials / ingredients.", "Two authorities or statutory hooks.", "One distinction or critique if the verb is \u2018critically examine\u2019.", "Close answering the exact question asked."]}],
        check: ["Can state the core definition without notes.", "Can list essentials in exam order.", "Can name at least two statutes, sections, or landmark cases for this heading."]
      },
      {
        id: "p-asylum",
        seq: 10,
        readAs: "Unit II \u00b7 asylum",
        unit: 2,
        yield: "high",
        tags: ["asylum", "refuge"],
        title: "Asylum",
        summary: "Territorial vs extraterritorial (diplomatic) asylum, non-refoulement neighbourhood, and why embassies are not automatic safe rooms. Contrast asylum with extradition in one tight table.",
        explainer: "<p class=\"stub\"><strong>Shell stub.</strong> Full concept write-up pending. Work from the CCS syllabus heading, the bare Act / public case names, and your primary textbook \u2014 this card will expand without copying Unique/Nitin prose.</p><p>Draft path: define \u2192 essentials \u2192 statutes/cases \u2192 one distinction \u2192 close to the exam verb.</p>",
        diagram: {"type": "flow", "title": "Stub map \u2014 Asylum", "steps": ["Syllabus heading", "Bare-act hooks", "Essentials list", "Timed outline", "Seal"]},
        mnemonic: {"name": "TBD", "hook": "Mnemonic pending \u2014 write your own after the first textbook pass.", "recite": "Replace this when the full card lands."},
        cases: [],
        pyqs: [{"year": "theme", "section": "\u2014", "marks": "10\u201320", "q": "PYQ outline placeholder \u2014 public CCS themes will be mapped here later.", "outline": ["Open with a one-line definition tied to the statute or doctrine.", "Numbered essentials / ingredients.", "Two authorities or statutory hooks.", "One distinction or critique if the verb is \u2018critically examine\u2019.", "Close answering the exact question asked."]}],
        check: ["Can state the core definition without notes.", "Can list essentials in exam order.", "Can name at least two statutes, sections, or landmark cases for this heading."]
      },
      {
        id: "p-war",
        seq: 11,
        readAs: "Unit III \u00b7 war & disputes",
        unit: 3,
        yield: "high",
        tags: ["war", "disputes", "icj"],
        title: "War, disputes, and peaceful settlement",
        summary: "Legal characterisation of war/armed conflict, peaceful means (negotiation, mediation, arbitration, ICJ), and UN collective security sketches. Keep dispute-settlement methods as a memorisable ladder.",
        explainer: "<p class=\"stub\"><strong>Shell stub.</strong> Full concept write-up pending. Work from the CCS syllabus heading, the bare Act / public case names, and your primary textbook \u2014 this card will expand without copying Unique/Nitin prose.</p><p>Draft path: define \u2192 essentials \u2192 statutes/cases \u2192 one distinction \u2192 close to the exam verb.</p>",
        diagram: {"type": "flow", "title": "Stub map \u2014 War, disputes, and peaceful settlement", "steps": ["Syllabus heading", "Bare-act hooks", "Essentials list", "Timed outline", "Seal"]},
        mnemonic: {"name": "TBD", "hook": "Mnemonic pending \u2014 write your own after the first textbook pass.", "recite": "Replace this when the full card lands."},
        cases: [],
        pyqs: [{"year": "theme", "section": "\u2014", "marks": "10\u201320", "q": "PYQ outline placeholder \u2014 public CCS themes will be mapped here later.", "outline": ["Open with a one-line definition tied to the statute or doctrine.", "Numbered essentials / ingredients.", "Two authorities or statutory hooks.", "One distinction or critique if the verb is \u2018critically examine\u2019.", "Close answering the exact question asked."]}],
        check: ["Can state the core definition without notes.", "Can list essentials in exam order.", "Can name at least two statutes, sections, or landmark cases for this heading."]
      },
      {
        id: "p-special",
        seq: 12,
        readAs: "Unit III \u00b7 special topics",
        unit: 3,
        yield: "high",
        tags: ["hijacking", "narcotics", "aliens", "contraband", "blockade", "terrorism"],
        title: "Hijacking, narcotics, aliens, enemy character, contraband, blockade, terrorism",
        summary: "A cluster of special topics that often appear as short notes: aerial hijacking conventions, narcotics traffic cooperation, status of aliens, enemy character in war, contraband and blockade, and terrorism as a transnational crime theme. One card, many 4\u201310 markers.",
        explainer: "<p class=\"stub\"><strong>Shell stub.</strong> Full concept write-up pending. Work from the CCS syllabus heading, the bare Act / public case names, and your primary textbook \u2014 this card will expand without copying Unique/Nitin prose.</p><p>Draft path: define \u2192 essentials \u2192 statutes/cases \u2192 one distinction \u2192 close to the exam verb.</p>",
        diagram: {"type": "flow", "title": "Stub map \u2014 Hijacking, narcotics, aliens, enemy char", "steps": ["Syllabus heading", "Bare-act hooks", "Essentials list", "Timed outline", "Seal"]},
        mnemonic: {"name": "TBD", "hook": "Mnemonic pending \u2014 write your own after the first textbook pass.", "recite": "Replace this when the full card lands."},
        cases: [],
        pyqs: [{"year": "theme", "section": "\u2014", "marks": "10\u201320", "q": "PYQ outline placeholder \u2014 public CCS themes will be mapped here later.", "outline": ["Open with a one-line definition tied to the statute or doctrine.", "Numbered essentials / ingredients.", "Two authorities or statutory hooks.", "One distinction or critique if the verb is \u2018critically examine\u2019.", "Close answering the exact question asked."]}],
        check: ["Can state the core definition without notes.", "Can list essentials in exam order.", "Can name at least two statutes, sections, or landmark cases for this heading."]
      },
      {
        id: "p-sea",
        seq: 13,
        readAs: "Unit III \u00b7 law of the sea",
        unit: 3,
        yield: "high",
        tags: ["unclos", "eez", "continental shelf", "territorial sea"],
        title: "Law of the Sea \u2014 belt, contiguous zone, EEZ, continental shelf",
        summary: "UNCLOS zones: baseline \u2192 territorial sea \u2192 contiguous zone \u2192 EEZ \u2192 continental shelf \u2192 high seas. Breadths, coastal-State rights, and innocent passage are the usual diagram-and-list ask.",
        explainer: "<p class=\"stub\"><strong>Shell stub.</strong> Full concept write-up pending. Work from the CCS syllabus heading, the bare Act / public case names, and your primary textbook \u2014 this card will expand without copying Unique/Nitin prose.</p><p>Draft path: define \u2192 essentials \u2192 statutes/cases \u2192 one distinction \u2192 close to the exam verb.</p>",
        diagram: {"type": "flow", "title": "Stub map \u2014 Law of the Sea", "steps": ["Syllabus heading", "Bare-act hooks", "Essentials list", "Timed outline", "Seal"]},
        mnemonic: {"name": "TBD", "hook": "Mnemonic pending \u2014 write your own after the first textbook pass.", "recite": "Replace this when the full card lands."},
        cases: [],
        pyqs: [{"year": "theme", "section": "\u2014", "marks": "10\u201320", "q": "PYQ outline placeholder \u2014 public CCS themes will be mapped here later.", "outline": ["Open with a one-line definition tied to the statute or doctrine.", "Numbered essentials / ingredients.", "Two authorities or statutory hooks.", "One distinction or critique if the verb is \u2018critically examine\u2019.", "Close answering the exact question asked."]}],
        check: ["Can state the core definition without notes.", "Can list essentials in exam order.", "Can name at least two statutes, sections, or landmark cases for this heading."]
      },
    ]
  };
})(window);
