(function (g) {
  g.LLB = g.LLB || {};
  g.LLB.papers = g.LLB.papers || {};
  g.LLB.papers.k3004 = {
    id: "k3004",
    code: "K-3004",
    title: "Law of Property and Easement",
    short: "Property",
    blurb: "TPA preliminaries through actionable claims, plus Indian Easements Act overview \u2014 stub teasers only.",
    shelf: {
      primary: "CCS-recommended Property text (e.g. R.K. Sinha / G.P. Tripathi college list) + Transfer of Property Act & Easements Act bare"
    },
    youtube: [
      { title: "TPA transfer and 53A", search: "Transfer of Property Act section 53A part performance" },
      { title: "Types of mortgage", search: "Types of mortgage TPA simple English usufructuary" },
      { title: "Easements essentials", search: "Indian Easements Act prescription easement" },
    ],
    topics: [
      {
        id: "pr-prelim",
        seq: 1,
        readAs: "Ss. 1\u20134",
        unit: 1,
        yield: "standard",
        tags: ["tpa", "preliminary", "definitions"],
        title: "Preliminary \u2014 TPA Ss. 1\u20134",
        summary: "Commencement, extent, definitions, and interpretation rules that every Transfer of Property answer quietly depends on. Immovable property, instrument, and attested/registered vocabulary show up in problem questions.",
        explainer: "<p class=\"stub\"><strong>Shell stub.</strong> Full concept write-up pending. Work from the CCS syllabus heading, the bare Act / public case names, and your primary textbook \u2014 this card will expand without copying Unique/Nitin prose.</p><p>Draft path: define \u2192 essentials \u2192 statutes/cases \u2192 one distinction \u2192 close to the exam verb.</p>",
        diagram: {"type": "flow", "title": "Stub map \u2014 Preliminary", "steps": ["Syllabus heading", "Bare-act hooks", "Essentials list", "Timed outline", "Seal"]},
        mnemonic: {"name": "TBD", "hook": "Mnemonic pending \u2014 write your own after the first textbook pass.", "recite": "Replace this when the full card lands."},
        cases: [],
        pyqs: [{"year": "theme", "section": "\u2014", "marks": "10\u201320", "q": "PYQ outline placeholder \u2014 public CCS themes will be mapped here later.", "outline": ["Open with a one-line definition tied to the statute or doctrine.", "Numbered essentials / ingredients.", "Two authorities or statutory hooks.", "One distinction or critique if the verb is \u2018critically examine\u2019.", "Close answering the exact question asked."]}],
        check: ["Can state the core definition without notes.", "Can list essentials in exam order.", "Can name at least two statutes, sections, or landmark cases for this heading."]
      },
      {
        id: "pr-transfer",
        seq: 2,
        readAs: "Ss. 5\u201353A",
        unit: 1,
        yield: "high",
        tags: ["transfer", "53a", "lis pendens", "election"],
        title: "Transfer of property \u2014 Ss. 5\u201337 & immovable Ss. 38\u201353A",
        summary: "What is a transfer, who can transfer, conditional transfers, election, apportionment, and the immovable-property special rules through lis pendens, fraudulent transfer, part-performance (53A). This is the conceptual engine of the paper.",
        explainer: "<p class=\"stub\"><strong>Shell stub.</strong> Full concept write-up pending. Work from the CCS syllabus heading, the bare Act / public case names, and your primary textbook \u2014 this card will expand without copying Unique/Nitin prose.</p><p>Draft path: define \u2192 essentials \u2192 statutes/cases \u2192 one distinction \u2192 close to the exam verb.</p>",
        diagram: {"type": "flow", "title": "Stub map \u2014 Transfer of property", "steps": ["Syllabus heading", "Bare-act hooks", "Essentials list", "Timed outline", "Seal"]},
        mnemonic: {"name": "TBD", "hook": "Mnemonic pending \u2014 write your own after the first textbook pass.", "recite": "Replace this when the full card lands."},
        cases: [],
        pyqs: [{"year": "theme", "section": "\u2014", "marks": "10\u201320", "q": "PYQ outline placeholder \u2014 public CCS themes will be mapped here later.", "outline": ["Open with a one-line definition tied to the statute or doctrine.", "Numbered essentials / ingredients.", "Two authorities or statutory hooks.", "One distinction or critique if the verb is \u2018critically examine\u2019.", "Close answering the exact question asked."]}],
        check: ["Can state the core definition without notes.", "Can list essentials in exam order.", "Can name at least two statutes, sections, or landmark cases for this heading."]
      },
      {
        id: "pr-sale",
        seq: 3,
        readAs: "Ss. 54\u201357",
        unit: 2,
        yield: "high",
        tags: ["sale", "section 54"],
        title: "Sale of immovable property \u2014 Ss. 54\u201357",
        summary: "Sale defined, how it is made (registered instrument where required), rights/liabilities of buyer and seller, and marshalling. Keep the \u2018contract for sale vs sale\u2019 distinction exam-ready.",
        explainer: "<p class=\"stub\"><strong>Shell stub.</strong> Full concept write-up pending. Work from the CCS syllabus heading, the bare Act / public case names, and your primary textbook \u2014 this card will expand without copying Unique/Nitin prose.</p><p>Draft path: define \u2192 essentials \u2192 statutes/cases \u2192 one distinction \u2192 close to the exam verb.</p>",
        diagram: {"type": "flow", "title": "Stub map \u2014 Sale of immovable property", "steps": ["Syllabus heading", "Bare-act hooks", "Essentials list", "Timed outline", "Seal"]},
        mnemonic: {"name": "TBD", "hook": "Mnemonic pending \u2014 write your own after the first textbook pass.", "recite": "Replace this when the full card lands."},
        cases: [],
        pyqs: [{"year": "theme", "section": "\u2014", "marks": "10\u201320", "q": "PYQ outline placeholder \u2014 public CCS themes will be mapped here later.", "outline": ["Open with a one-line definition tied to the statute or doctrine.", "Numbered essentials / ingredients.", "Two authorities or statutory hooks.", "One distinction or critique if the verb is \u2018critically examine\u2019.", "Close answering the exact question asked."]}],
        check: ["Can state the core definition without notes.", "Can list essentials in exam order.", "Can name at least two statutes, sections, or landmark cases for this heading."]
      },
      {
        id: "pr-mortgage",
        seq: 4,
        readAs: "Ss. 58\u2013104",
        unit: 2,
        yield: "high",
        tags: ["mortgage", "charge", "redemption"],
        title: "Mortgages and charges \u2014 Ss. 58\u2013104",
        summary: "Simple, mortgage by conditional sale, usufructuary, English, equitable flavours in Indian statutory dress; rights of mortgagor/mortgagee; charge vs mortgage. Diagram the six (classic) forms and redemption/foreclosure vocabulary.",
        explainer: "<p class=\"stub\"><strong>Shell stub.</strong> Full concept write-up pending. Work from the CCS syllabus heading, the bare Act / public case names, and your primary textbook \u2014 this card will expand without copying Unique/Nitin prose.</p><p>Draft path: define \u2192 essentials \u2192 statutes/cases \u2192 one distinction \u2192 close to the exam verb.</p>",
        diagram: {"type": "flow", "title": "Stub map \u2014 Mortgages and charges", "steps": ["Syllabus heading", "Bare-act hooks", "Essentials list", "Timed outline", "Seal"]},
        mnemonic: {"name": "TBD", "hook": "Mnemonic pending \u2014 write your own after the first textbook pass.", "recite": "Replace this when the full card lands."},
        cases: [],
        pyqs: [{"year": "theme", "section": "\u2014", "marks": "10\u201320", "q": "PYQ outline placeholder \u2014 public CCS themes will be mapped here later.", "outline": ["Open with a one-line definition tied to the statute or doctrine.", "Numbered essentials / ingredients.", "Two authorities or statutory hooks.", "One distinction or critique if the verb is \u2018critically examine\u2019.", "Close answering the exact question asked."]}],
        check: ["Can state the core definition without notes.", "Can list essentials in exam order.", "Can name at least two statutes, sections, or landmark cases for this heading."]
      },
      {
        id: "pr-lease",
        seq: 5,
        readAs: "Ss. 105\u2013117",
        unit: 2,
        yield: "high",
        tags: ["lease", "licence", "forfeiture"],
        title: "Leases \u2014 Ss. 105\u2013117",
        summary: "Lease essentials, duration, rights/liabilities, determination, and holding over. Contrast lease with licence; notice and forfeiture themes are frequent problem-spines.",
        explainer: "<p class=\"stub\"><strong>Shell stub.</strong> Full concept write-up pending. Work from the CCS syllabus heading, the bare Act / public case names, and your primary textbook \u2014 this card will expand without copying Unique/Nitin prose.</p><p>Draft path: define \u2192 essentials \u2192 statutes/cases \u2192 one distinction \u2192 close to the exam verb.</p>",
        diagram: {"type": "flow", "title": "Stub map \u2014 Leases", "steps": ["Syllabus heading", "Bare-act hooks", "Essentials list", "Timed outline", "Seal"]},
        mnemonic: {"name": "TBD", "hook": "Mnemonic pending \u2014 write your own after the first textbook pass.", "recite": "Replace this when the full card lands."},
        cases: [],
        pyqs: [{"year": "theme", "section": "\u2014", "marks": "10\u201320", "q": "PYQ outline placeholder \u2014 public CCS themes will be mapped here later.", "outline": ["Open with a one-line definition tied to the statute or doctrine.", "Numbered essentials / ingredients.", "Two authorities or statutory hooks.", "One distinction or critique if the verb is \u2018critically examine\u2019.", "Close answering the exact question asked."]}],
        check: ["Can state the core definition without notes.", "Can list essentials in exam order.", "Can name at least two statutes, sections, or landmark cases for this heading."]
      },
      {
        id: "pr-exchange",
        seq: 6,
        readAs: "Ss. 118\u2013121",
        unit: 3,
        yield: "standard",
        tags: ["exchange"],
        title: "Exchange \u2014 Ss. 118\u2013121",
        summary: "Exchange as mutual transfer of ownership of one thing for another \u2014 sale rules applied with modifications. Short but clean: definition, parties\u2019 duties, and difference from sale.",
        explainer: "<p class=\"stub\"><strong>Shell stub.</strong> Full concept write-up pending. Work from the CCS syllabus heading, the bare Act / public case names, and your primary textbook \u2014 this card will expand without copying Unique/Nitin prose.</p><p>Draft path: define \u2192 essentials \u2192 statutes/cases \u2192 one distinction \u2192 close to the exam verb.</p>",
        diagram: {"type": "flow", "title": "Stub map \u2014 Exchange", "steps": ["Syllabus heading", "Bare-act hooks", "Essentials list", "Timed outline", "Seal"]},
        mnemonic: {"name": "TBD", "hook": "Mnemonic pending \u2014 write your own after the first textbook pass.", "recite": "Replace this when the full card lands."},
        cases: [],
        pyqs: [{"year": "theme", "section": "\u2014", "marks": "10\u201320", "q": "PYQ outline placeholder \u2014 public CCS themes will be mapped here later.", "outline": ["Open with a one-line definition tied to the statute or doctrine.", "Numbered essentials / ingredients.", "Two authorities or statutory hooks.", "One distinction or critique if the verb is \u2018critically examine\u2019.", "Close answering the exact question asked."]}],
        check: ["Can state the core definition without notes.", "Can list essentials in exam order.", "Can name at least two statutes, sections, or landmark cases for this heading."]
      },
      {
        id: "pr-gift",
        seq: 7,
        readAs: "Ss. 122\u2013129",
        unit: 3,
        yield: "high",
        tags: ["gift", "tpa gift"],
        title: "Gifts \u2014 Ss. 122\u2013129",
        summary: "Gift under TPA: transfer without consideration, registered instrument for immovable property, acceptance, and suspension/revocation limits. Distinguish TPA gift from Muslim hiba when the paper cross-fires Family Law.",
        explainer: "<p class=\"stub\"><strong>Shell stub.</strong> Full concept write-up pending. Work from the CCS syllabus heading, the bare Act / public case names, and your primary textbook \u2014 this card will expand without copying Unique/Nitin prose.</p><p>Draft path: define \u2192 essentials \u2192 statutes/cases \u2192 one distinction \u2192 close to the exam verb.</p>",
        diagram: {"type": "flow", "title": "Stub map \u2014 Gifts", "steps": ["Syllabus heading", "Bare-act hooks", "Essentials list", "Timed outline", "Seal"]},
        mnemonic: {"name": "TBD", "hook": "Mnemonic pending \u2014 write your own after the first textbook pass.", "recite": "Replace this when the full card lands."},
        cases: [],
        pyqs: [{"year": "theme", "section": "\u2014", "marks": "10\u201320", "q": "PYQ outline placeholder \u2014 public CCS themes will be mapped here later.", "outline": ["Open with a one-line definition tied to the statute or doctrine.", "Numbered essentials / ingredients.", "Two authorities or statutory hooks.", "One distinction or critique if the verb is \u2018critically examine\u2019.", "Close answering the exact question asked."]}],
        check: ["Can state the core definition without notes.", "Can list essentials in exam order.", "Can name at least two statutes, sections, or landmark cases for this heading."]
      },
      {
        id: "pr-actionable",
        seq: 8,
        readAs: "Ss. 130\u2013137",
        unit: 3,
        yield: "standard",
        tags: ["actionable claim", "assignment"],
        title: "Actionable claims \u2014 Ss. 130\u2013137",
        summary: "Actionable claim as a claim to unsecured debt or beneficial interest in movables not in possession \u2014 assignment formalities and notice. Often a crisp short note; nail the definition and mode of transfer.",
        explainer: "<p class=\"stub\"><strong>Shell stub.</strong> Full concept write-up pending. Work from the CCS syllabus heading, the bare Act / public case names, and your primary textbook \u2014 this card will expand without copying Unique/Nitin prose.</p><p>Draft path: define \u2192 essentials \u2192 statutes/cases \u2192 one distinction \u2192 close to the exam verb.</p>",
        diagram: {"type": "flow", "title": "Stub map \u2014 Actionable claims", "steps": ["Syllabus heading", "Bare-act hooks", "Essentials list", "Timed outline", "Seal"]},
        mnemonic: {"name": "TBD", "hook": "Mnemonic pending \u2014 write your own after the first textbook pass.", "recite": "Replace this when the full card lands."},
        cases: [],
        pyqs: [{"year": "theme", "section": "\u2014", "marks": "10\u201320", "q": "PYQ outline placeholder \u2014 public CCS themes will be mapped here later.", "outline": ["Open with a one-line definition tied to the statute or doctrine.", "Numbered essentials / ingredients.", "Two authorities or statutory hooks.", "One distinction or critique if the verb is \u2018critically examine\u2019.", "Close answering the exact question asked."]}],
        check: ["Can state the core definition without notes.", "Can list essentials in exam order.", "Can name at least two statutes, sections, or landmark cases for this heading."]
      },
      {
        id: "pr-easement",
        seq: 9,
        readAs: "Easements Act overview",
        unit: 3,
        yield: "high",
        tags: ["easement", "prescription"],
        title: "Indian Easements Act \u2014 overview",
        summary: "Easement as a right over another\u2019s land for beneficial enjoyment of one\u2019s own: continuous/discontinuous, apparent/non-apparent; acquisition by prescription, grant, necessity; extinction. Keep a definition + modes + extinction triad.",
        explainer: "<p class=\"stub\"><strong>Shell stub.</strong> Full concept write-up pending. Work from the CCS syllabus heading, the bare Act / public case names, and your primary textbook \u2014 this card will expand without copying Unique/Nitin prose.</p><p>Draft path: define \u2192 essentials \u2192 statutes/cases \u2192 one distinction \u2192 close to the exam verb.</p>",
        diagram: {"type": "flow", "title": "Stub map \u2014 Indian Easements Act", "steps": ["Syllabus heading", "Bare-act hooks", "Essentials list", "Timed outline", "Seal"]},
        mnemonic: {"name": "TBD", "hook": "Mnemonic pending \u2014 write your own after the first textbook pass.", "recite": "Replace this when the full card lands."},
        cases: [],
        pyqs: [{"year": "theme", "section": "\u2014", "marks": "10\u201320", "q": "PYQ outline placeholder \u2014 public CCS themes will be mapped here later.", "outline": ["Open with a one-line definition tied to the statute or doctrine.", "Numbered essentials / ingredients.", "Two authorities or statutory hooks.", "One distinction or critique if the verb is \u2018critically examine\u2019.", "Close answering the exact question asked."]}],
        check: ["Can state the core definition without notes.", "Can list essentials in exam order.", "Can name at least two statutes, sections, or landmark cases for this heading."]
      },
    ]
  };
})(window);
